Repository googleapis/nodejs-dataproc, pull requests merged in 2019-03, with the labels that each got.

#170 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#169 chore: sync proto documentation changes
  protos/google/cloud/dataproc/v1beta2/clusters.proto
  src/v1beta2/doc/google/cloud/dataproc/v1beta2/doc_clusters.js
  synth.metadata
Labels: :rotating_light:, cla: yes

#171 chore: sync latest proto docs & kokoro publish config
  .kokoro/release/publish.cfg
  protos/google/cloud/dataproc/v1/clusters.proto
  protos/google/cloud/dataproc/v1/jobs.proto
  protos/google/cloud/dataproc/v1/operations.proto
  protos/google/cloud/dataproc/v1/workflow_templates.proto
  protos/google/cloud/dataproc/v1beta2/clusters.proto
  protos/google/cloud/dataproc/v1beta2/jobs.proto
  protos/google/cloud/dataproc/v1beta2/operations.proto
  protos/google/cloud/dataproc/v1beta2/shared.proto
  protos/google/cloud/dataproc/v1beta2/workflow_templates.proto
  src/v1/cluster_controller_client.js
  src/v1/doc/google/cloud/dataproc/v1/doc_clusters.js
  src/v1/doc/google/cloud/dataproc/v1/doc_jobs.js
  src/v1/doc/google/cloud/dataproc/v1/doc_workflow_templates.js
  src/v1/doc/google/rpc/doc_status.js
  src/v1/job_controller_client.js
  src/v1/workflow_template_service_client.js
  src/v1beta2/cluster_controller_client.js
  src/v1beta2/doc/google/cloud/dataproc/v1beta2/doc_clusters.js
  src/v1beta2/doc/google/cloud/dataproc/v1beta2/doc_jobs.js
  src/v1beta2/doc/google/cloud/dataproc/v1beta2/doc_workflow_templates.js
  src/v1beta2/doc/google/rpc/doc_status.js
  src/v1beta2/job_controller_client.js
  src/v1beta2/workflow_template_service_client.js
  synth.metadata
Labels: cla: yes

#172 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#174 Release @google-cloud/dataproc v0.5.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#177 fix(docs): fix a broken link
  src/v1beta2/doc/google/cloud/dataproc/v1beta2/doc_clusters.js
  synth.py
Labels: cla: yes

#179 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#181 docs: update docstring samples and use json import paths
  src/v1/cluster_controller_client.js
  src/v1/doc/google/longrunning/doc_operations.js
  src/v1/job_controller_client.js
  src/v1/workflow_template_service_client.js
  src/v1beta2/cluster_controller_client.js
  src/v1beta2/doc/google/longrunning/doc_operations.js
  src/v1beta2/job_controller_client.js
  src/v1beta2/workflow_template_service_client.js
  synth.metadata
Labels: cla: yes

#182 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#186 fix: include 'x-goog-request-params' header in requests
  src/v1/workflow_template_service_client.js
  src/v1beta2/workflow_template_service_client.js
  synth.metadata
Labels: cla: yes
