Repository googleapis/nodejs-dataproc, pull requests merged in 2019-05, with the labels that each got.

#194 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#195 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#196 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#199 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#201 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#200 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#198 build: only pipe to codecov if tests run in Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#202 fix: DEADLINE_EXCEEDED is no longer retried
  src/v1/cluster_controller_client_config.json
  src/v1/job_controller_client_config.json
  src/v1/workflow_template_service_client_config.json
  src/v1beta2/cluster_controller_client_config.json
  src/v1beta2/job_controller_client_config.json
  src/v1beta2/workflow_template_service_client_config.json
  synth.metadata
Labels: cla: yes

#204 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1/cluster_controller_client_config.json
  src/v1/job_controller_client_config.json
  src/v1/workflow_template_service_client_config.json
  src/v1beta2/cluster_controller_client_config.json
  src/v1beta2/job_controller_client_config.json
  src/v1beta2/workflow_template_service_client_config.json
  synth.metadata
Labels: cla: yes

#206 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#210 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#212 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/cluster_controller_client.js
  src/v1/job_controller_client.js
  src/v1/workflow_template_service_client.js
  src/v1beta2/cluster_controller_client.js
  src/v1beta2/job_controller_client.js
  src/v1beta2/workflow_template_service_client.js
  synth.metadata
Labels: cla: yes

#213 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#214 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#215 feat: add support for autoscaling policies
  protos/google/cloud/dataproc/v1beta2/autoscaling_policies.proto
  protos/google/cloud/dataproc/v1beta2/clusters.proto
  protos/google/cloud/dataproc/v1beta2/jobs.proto
  protos/google/cloud/dataproc/v1beta2/operations.proto
  protos/google/cloud/dataproc/v1beta2/shared.proto
  protos/google/cloud/dataproc/v1beta2/workflow_templates.proto
  src/v1beta2/autoscaling_policy_service_client.js
  src/v1beta2/autoscaling_policy_service_client_config.json
  src/v1beta2/cluster_controller_client.js
  src/v1beta2/doc/google/cloud/dataproc/v1beta2/doc_autoscaling_policies.js
  src/v1beta2/doc/google/cloud/dataproc/v1beta2/doc_clusters.js
  src/v1beta2/doc/google/cloud/dataproc/v1beta2/doc_jobs.js
  src/v1beta2/doc/google/cloud/dataproc/v1beta2/doc_workflow_templates.js
  src/v1beta2/index.js
  src/v1beta2/job_controller_client.js
  src/v1beta2/workflow_template_service_client.js
  synth.metadata
  test/gapic-v1beta2.js
Labels: cla: yes

#216 chore: release 1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#218 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#219 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#221 feat: add support for cluster components
  package.json
  protos/google/cloud/dataproc/v1/clusters.proto
  protos/google/cloud/dataproc/v1/jobs.proto
  protos/google/cloud/dataproc/v1/operations.proto
  protos/google/cloud/dataproc/v1/shared.proto
  protos/google/cloud/dataproc/v1/workflow_templates.proto
  src/v1/cluster_controller_client.js
  src/v1/doc/google/cloud/dataproc/v1/doc_clusters.js
  src/v1/doc/google/cloud/dataproc/v1/doc_jobs.js
  src/v1/doc/google/cloud/dataproc/v1/doc_workflow_templates.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/job_controller_client.js
  src/v1/workflow_template_service_client.js
  src/v1beta2/doc/google/protobuf/doc_timestamp.js
  synth.metadata
  synth.py
Labels: cla: yes
