Repository googleapis/nodejs-dataproc, pull requests merged in 2020-11, with the labels that each got.

#443 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full

#445 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/autoscaling_policy_service_client.ts
  src/v1/cluster_controller_client.ts
  src/v1/job_controller_client.ts
  src/v1/workflow_template_service_client.ts
  src/v1beta2/autoscaling_policy_service_client.ts
  src/v1beta2/cluster_controller_client.ts
  src/v1beta2/job_controller_client.ts
  src/v1beta2/workflow_template_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: dataproc, automerge, cla: yes

#447 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/autoscaling_policy_service_client.ts
  src/v1/cluster_controller_client.ts
  src/v1/job_controller_client.ts
  src/v1/workflow_template_service_client.ts
  src/v1beta2/autoscaling_policy_service_client.ts
  src/v1beta2/cluster_controller_client.ts
  src/v1beta2/job_controller_client.ts
  src/v1beta2/workflow_template_service_client.ts
  synth.metadata
Labels: api: dataproc, cla: yes, context: none

#450 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: dataproc, automerge, cla: yes, context: full
