Repository googleapis/nodejs-dataproc, pull requests merged in 2020-05, with the labels that each got.

#372 feat: check status of long running operation by its name
  protos/protos.js
  src/v1/cluster_controller_client.ts
  src/v1/job_controller_client.ts
  src/v1/workflow_template_service_client.ts
  src/v1beta2/cluster_controller_client.ts
  src/v1beta2/job_controller_client.ts
  src/v1beta2/workflow_template_service_client.ts
  synth.metadata
  test/gapic_autoscaling_policy_service_v1.ts
  test/gapic_autoscaling_policy_service_v1beta2.ts
  test/gapic_cluster_controller_v1.ts
  test/gapic_cluster_controller_v1beta2.ts
  test/gapic_job_controller_v1.ts
  test/gapic_job_controller_v1beta2.ts
  test/gapic_workflow_template_service_v1.ts
  test/gapic_workflow_template_service_v1beta2.ts
Labels: automerge, cla: yes

#373 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#374 chore: linting rules
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#375 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#369 test: quickstart sometimes has service failures
  samples/system-test/quickstart.test.js
Labels: cla: yes

#379 build: default export in protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none
