Repository googleapis/nodejs-dataproc, pull requests merged in 2020-06, with the labels that each got.

#384 docs: updated links in protos, fix synth
  protos/google/cloud/dataproc/v1/jobs.proto
  protos/google/cloud/dataproc/v1beta2/jobs.proto
  synth.metadata
  synth.py
Labels: cla: yes

#385 chore: add proto3Optional field
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: none

#388 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/autoscaling_policy_service_client.ts
  src/v1/cluster_controller_client.ts
  src/v1/job_controller_client.ts
  src/v1/workflow_template_service_client.ts
  src/v1beta2/autoscaling_policy_service_client.ts
  src/v1beta2/cluster_controller_client.ts
  src/v1beta2/job_controller_client.ts
  src/v1beta2/workflow_template_service_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#391 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#392 fix: proper fallback option handling
  src/v1/autoscaling_policy_service_client.ts
  src/v1/cluster_controller_client.ts
  src/v1/job_controller_client.ts
  src/v1/workflow_template_service_client.ts
  src/v1beta2/autoscaling_policy_service_client.ts
  src/v1beta2/cluster_controller_client.ts
  src/v1beta2/job_controller_client.ts
  src/v1beta2/workflow_template_service_client.ts
  synth.metadata
Labels: cla: yes, context: none

#393 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#395 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
