Repository googleapis/nodejs-dataproc, pull requests merged in 2020-07, with the labels that each got.

#397 build: use bazel build
  src/v1/autoscaling_policy_service_client.ts
  src/v1/workflow_template_service_client.ts
  src/v1beta2/autoscaling_policy_service_client.ts
  src/v1beta2/workflow_template_service_client.ts
  synth.metadata
  synth.py
  test/gapic_autoscaling_policy_service_v1.ts
  test/gapic_autoscaling_policy_service_v1beta2.ts
  test/gapic_workflow_template_service_v1.ts
  test/gapic_workflow_template_service_v1beta2.ts
Labels: automerge, cla: yes

#398 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#396 chore(samples): no native sleep
  samples/package.json
  samples/quickstart.js
Labels: automerge, cla: yes

#400 refactor: sleep timer
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#403 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#404 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#405 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#409 fix: LRO annotations for method `DiagnoseCluster`.
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/google/cloud/dataproc/v1/clusters.proto
  protos/protos.json
  src/v1/cluster_controller_client.ts
  synth.metadata
  test/gapic_cluster_controller_v1.ts
Labels: cla: yes, context: partial

#410 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#412 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#413 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#414 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#415 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#416 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#417 feat: Additional fields for the `ClusterConfig` and `InstanceGroupConfig, update protos
  protos/google/cloud/dataproc/v1/autoscaling_policies.proto
  protos/google/cloud/dataproc/v1/clusters.proto
  protos/google/cloud/dataproc/v1/jobs.proto
  protos/google/cloud/dataproc/v1/shared.proto
  protos/google/cloud/dataproc/v1/workflow_templates.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: partial

#420 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
